apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-webServer.fullname" . }}
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <title>This is the title of the webpage!</title>
      </head>
      <body>
        <p>Test-html</p>
      </body>
    </html>